#server.port=${PORT:9090}
#server.servlet.context-path = /workphoto
server.max-http-header-size=4MB

# Ensure the database stores the file path, not the blob
spring.servlet.multipart.max-file-size = 50MB
spring.servlet.multipart.max-request-size = 100MB
spring.servlet.multipart.enabled = false

spring.datasource.url = jdbc:mariadb://localhost:3306/catchghostdb
spring.datasource.username = dbadmin
spring.datasource.password = admindb
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto = none
spring.jpa.defer-datasource-initialization = true

spring.sql.init.mode = never

vaadin.launch-browser = true
vaadin.productionMode = true
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.rickqin.catchghost

# App config
#app.upload.directory = ../workorder_photos
#app.workorder.validation = ^[0-9]{6}$
